#!/usr/bin/env python3
"""Builds website/privacy.html and website/terms.html from the app's own
PRIVACY_POLICY.md and TERMS_OF_SERVICE.md, so the site and the app can never
say different things. Run from the repo root after editing either document:

    python3 tools/legal_pages.py

The markdown is the small subset those two files use: # and ## headings,
paragraphs, "- " lists whose items wrap onto indented lines, **bold**,
*italic* and [links](url).
"""
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PAGES = [
    ("PRIVACY_POLICY.md", "website/privacy.html", "Privacy Policy",
     "How 808 handles your information: what stays on your phone, what syncs to your own iCloud, and what we can see."),
    ("TERMS_OF_SERVICE.md", "website/terms.html", "Terms of Service",
     "The terms for using the 808 meditation app."),
]


def inline(text):
    text = html.escape(text, quote=False)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?![*\w])", r"<em>\1</em>", text)
    return text


def convert(md):
    lines = md.splitlines()
    out, para, items = [], [], []
    title, updated = "", ""

    def flush_para():
        if para:
            out.append("<p>" + inline(" ".join(para)) + "</p>")
            para.clear()

    def flush_list():
        if items:
            out.append("<ul>" + "".join("<li>" + inline(" ".join(i)) + "</li>" for i in items) + "</ul>")
            items.clear()

    for raw in lines:
        line = raw.rstrip()
        if line.startswith("# "):
            title = line[2:].strip()
            continue
        if line.startswith("**Last updated"):
            updated = re.sub(r"\*", "", line).strip()
            continue
        if not line.strip():
            flush_para(); flush_list()
            continue
        if line.startswith("## "):
            flush_para(); flush_list()
            heading = line[3:].strip()
            slug = re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")
            out.append(f'<h2 id="{slug}">{inline(heading)}</h2>')
            continue
        if line.startswith("- "):
            flush_para()
            items.append([line[2:].strip()])
            continue
        if items and raw.startswith("  "):
            items[-1].append(line.strip())
            continue
        flush_list()
        para.append(line.strip())
    flush_para(); flush_list()
    return title, updated, "\n".join(out)


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>808 {title}</title>
<meta name="description" content="{description}">
<link rel="preload" href="fonts/nunito-var.woff2" as="font" type="font/woff2" crossorigin>
<link rel="icon" href="img/otto/ottohead.png">
<!-- Generated by tools/legal_pages.py from {source}. Edit that file, not this one. -->
<style>
  @font-face {{ font-family:'Nunito'; src:url('fonts/nunito-var.woff2') format('woff2');
    font-weight:200 1000; font-display:swap; }}
  :root{{
    --sky-top:#86BDE2; --sky-bot:#DCEEF6; --paper:#FBF8F2; --sand:#F0E9DC; --sand-edge:#E2D8C6;
    --ink:#2A231E; --ink-soft:#5E554D; --ink-faint:#A1978C;
    --green:#5AB950; --green-shade:#418E3A; --green-ink:#2F6E2A;
    --font:'Nunito', ui-rounded, 'SF Pro Rounded', system-ui, sans-serif;
  }}
  *{{ box-sizing:border-box; }}
  html{{ scroll-behavior:smooth; }}
  body{{ margin:0; background:var(--paper); color:var(--ink); font-family:var(--font);
    font-size:17.5px; line-height:1.65; -webkit-font-smoothing:antialiased; }}
  a{{ color:var(--green-ink); text-underline-offset:2px; }}
  a:focus-visible{{ outline:3px solid var(--green); outline-offset:3px; border-radius:6px; }}
  .top{{ background:linear-gradient(var(--sky-top), var(--sky-bot)); border-radius:0 0 36px 36px;
    padding:20px 20px 46px; }}
  .nav{{ max-width:760px; margin:0 auto; display:flex; align-items:center; justify-content:space-between; }}
  .brand{{ display:flex; align-items:center; gap:9px; color:var(--ink); text-decoration:none;
    font-weight:900; font-size:24px; letter-spacing:-.03em; }}
  .brand img{{ width:34px; height:34px; }}
  .back{{ font-weight:800; font-size:15px; color:#fff; text-decoration:none; background:var(--green);
    padding:9px 16px; border-radius:999px; box-shadow:0 3px 0 var(--green-shade); }}
  .top h1{{ max-width:760px; margin:40px auto 0; font-weight:900; font-size:clamp(36px,6vw,54px);
    letter-spacing:-.03em; line-height:1.05; }}
  .top .updated{{ max-width:760px; margin:10px auto 0; font-weight:700; color:#3E4A52; }}
  main{{ max-width:760px; margin:0 auto; padding:34px 20px 20px; }}
  .toc{{ background:var(--sand); border-radius:22px; padding:18px 22px; margin:0 0 30px; }}
  .toc b{{ display:block; font-weight:900; margin-bottom:6px; }}
  .toc ol{{ margin:0; padding-left:22px; columns:2; column-gap:28px; font-size:15.5px; font-weight:700; }}
  .toc li{{ margin:3px 0; break-inside:avoid; }}
  .toc a{{ text-decoration:none; }}
  h2{{ font-weight:900; font-size:clamp(22px,3vw,27px); letter-spacing:-.02em; line-height:1.2;
    margin:40px 0 10px; scroll-margin-top:20px; }}
  p, li{{ color:var(--ink-soft); }}
  strong{{ color:var(--ink); font-weight:800; }}
  ul{{ padding-left:22px; }}
  li{{ margin:6px 0; }}
  footer{{ max-width:760px; margin:40px auto 0; padding:26px 20px 50px; border-top:1px solid var(--sand-edge);
    display:flex; flex-wrap:wrap; gap:10px 22px; font-size:14.5px; font-weight:700; color:var(--ink-faint); }}
  footer a{{ color:var(--ink-soft); text-decoration:none; }}
  @media (max-width:600px){{ .toc ol{{ columns:1; }} }}
</style>
</head>
<body>
<div class="top">
  <nav class="nav">
    <a class="brand" href="index.html"><img src="img/otto/ottohead.png" alt="" width="34" height="34">808</a>
    <a class="back" href="index.html">Back to the site</a>
  </nav>
  <h1>{title}</h1>
  <p class="updated">{updated}</p>
</div>
<main>
  <nav class="toc" aria-label="Contents"><b>On this page</b><ol>{toc}</ol></nav>
{body}
</main>
<footer>
  <span>&copy; 2026 Lock Out Inc.</span>
  <a href="privacy.html">Privacy Policy</a>
  <a href="terms.html">Terms of Service</a>
  <a href="mailto:support@meditate808.com">support@meditate808.com</a>
</footer>
</body>
</html>
"""


def main():
    for source, target, fallback, description in PAGES:
        title, updated, body = convert((ROOT / source).read_text())
        toc = "".join(f'<li><a href="#{m.group(1)}">{m.group(2)}</a></li>'
                      for m in re.finditer(r'<h2 id="([^"]+)">(.+?)</h2>', body))
        page = TEMPLATE.format(title=title or fallback, updated=updated, body=body, toc=toc,
                               description=html.escape(description), source=source)
        (ROOT / target).write_text(page)
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
